---
title: "comparing LF and HF"
author: "MacManes"
date: "`r Sys.Date()`"
output: html_document
---

bring in libs

```{r import libraries message=FALSE, warning=FALSE, echo=FALSE}
library(devtools)
library(tidyverse)
library(lubridate)
library(readr)
library(viridis)
library(patchwork)
library(tidyselect)
library(readxl)
library(broom)
library(cowplot)
library(DescTools)
library(ggpubr)
library(plyr)
library(pwr)
library(Cairo)
library(ggpattern)
library(timeDate)
library(mgcv)
library(MASS)
library(dplyr)
```


```{r make plots}

coeff <- 0
cols <- c("Highfat Baseline"="navyblue","Lowfat Baseline"="sienna1")
lf_hf_baseline_temperatures <- ggplot(data = lowfat_baseline_temps ,aes(x=as.POSIXct(time),y=body_temp)) +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 00:00:01", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 06:00:00", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 21:00:00", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 23:59:59", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  geom_point(aes(color = "Lowfat Baseline", alpha=0.1), shape=21, size=1)+
  geom_point(data = highfat_baseline_temps, aes(color="Highfat Baseline", alpha=0.2), shape=20, size=0.5)+
  geom_point(data = chunk1, aes(x=as.POSIXct(time), y=Deg_C + coeff), size=1, color="black", shape=4)+
     labs(x = "")+
  theme_classic()+
  geom_smooth(method='gam', se = FALSE, aes(color = "Lowfat Baseline"), span=0.2, size=2)+
  geom_smooth(data = highfat_baseline_temps, method='gam', se = FALSE, aes(color = "Highfat Baseline"), size=2)+
  labs(x = "")+
  scale_y_continuous(name = "Body Temperature (°C)", limits = c(20,40), sec.axis = sec_axis(~. - coeff, name="Room Temperature (°C)"))+ 
  guides(alpha = "none")+
  facet_wrap(~sex) +
 scale_colour_manual(name="Dehydration",values=cols, guide="none")
lf_hf_baseline_temperatures


### DAY1

coeff <- 0
cols <- c("Highfat Baseline"="navyblue","Lowfat Baseline"="sienna1")
lf_hf_day1_temperatures <- ggplot(data = lowfat_day1_temps ,aes(x=as.POSIXct(time),y=body_temp)) +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 00:00:01", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 06:00:00", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 21:00:00", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 23:59:59", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  geom_point(aes(color = "Lowfat Baseline", alpha=0.1), shape=21, size=1)+
  geom_point(data = highfat_day1_temps, aes(color="Highfat Baseline", alpha=0.2), shape=20, size=0.5)+
  geom_point(data = chunk1, aes(x=as.POSIXct(time), y=Deg_C + coeff), size=1, color="black", shape=4)+
     labs(x = "")+
  theme_classic()+
  geom_smooth(method='gam', se = FALSE, aes(color = "Lowfat Baseline"), span=0.2, size=2)+
  geom_smooth(data = highfat_day1_temps, method='gam', se = FALSE, aes(color = "Highfat Baseline"), size=2)+
  labs(x = "")+
  scale_y_continuous(name = "Body Temperature (°C)", limits = c(20,40), sec.axis = sec_axis(~. - coeff, name="Room Temperature (°C)"))+ 
  guides(alpha = "none")+
  facet_wrap(~sex) +
 scale_colour_manual(name="Dehydration",values=cols, guide="none")
lf_hf_day1_temperatures

### DAY2

coeff <- 0
cols <- c("Highfat Baseline"="navyblue","Lowfat Baseline"="sienna1")
lf_hf_day2_temperatures <- ggplot(data = lowfat_day2_temps ,aes(x=as.POSIXct(time),y=body_temp)) +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 00:00:01", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 06:00:00", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 21:00:00", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 23:59:59", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  geom_point(aes(color = "Lowfat Baseline", alpha=0.1), shape=21, size=1)+
  geom_point(data = highfat_day2_temps, aes(color="Highfat Baseline", alpha=0.2), shape=20, size=0.5)+
  geom_point(data = chunk1, aes(x=as.POSIXct(time), y=Deg_C + coeff), size=1, color="black", shape=4)+
     labs(x = "")+
  theme_classic()+
  geom_smooth(method='gam', se = FALSE, aes(color = "Lowfat Baseline"), span=0.2, size=2)+
  geom_smooth(data = highfat_day2_temps, method='gam', se = FALSE, aes(color = "Highfat Baseline"), size=2)+
  labs(x = "")+
  scale_y_continuous(name = "Body Temperature (°C)", limits = c(20,40), sec.axis = sec_axis(~. - coeff, name="Room Temperature (°C)"))+ 
  guides(alpha = "none")+
  facet_wrap(~sex) +
 scale_colour_manual(name="Dehydration",values=cols, guide="none")
lf_hf_day2_temperatures


### DAY3

coeff <- 0
cols <- c("Highfat Baseline"="navyblue","Lowfat Baseline"="sienna1")
lf_hf_day3_temperatures <- ggplot(data = lowfat_day3_temps ,aes(x=as.POSIXct(time),y=body_temp)) +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 00:00:01", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 06:00:00", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  annotate("rect", xmin = as.POSIXct("1970-01-01 21:00:00", tz="UTC"), 
           xmax = as.POSIXct("1970-01-01 23:59:59", tz="UTC"), 
           ymin = -Inf, ymax = Inf, fill="grey84") +
  geom_point(aes(color = "Lowfat Baseline", alpha=0.1), shape=21, size=1)+
  geom_point(data = highfat_day3_temps, aes(color="Highfat Baseline", alpha=0.2), shape=20, size=0.5)+
  geom_point(data = chunk1, aes(x=as.POSIXct(time), y=Deg_C + coeff), size=1, color="black", shape=4)+
     labs(x = "")+
  theme_classic()+
  geom_smooth(method='gam', se = FALSE, aes(color = "Lowfat Baseline"), span=0.2, size=2)+
  geom_smooth(data = highfat_day3_temps, method='gam', se = FALSE, aes(color = "Highfat Baseline"), size=2)+
  labs(x = "")+
  scale_y_continuous(name = "Body Temperature (°C)", limits = c(20,40), sec.axis = sec_axis(~. - coeff, name="Room Temperature (°C)"))+ 
  guides(alpha = "none")+
  facet_wrap(~sex) +
 scale_colour_manual(name="Dehydration",values=cols, guide="none")
lf_hf_day3_temperatures

```